name: Build IK Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y scons g++ 

      # Restore cached build objects for godot-cpp, if available
      - name: Restore godot-cpp Cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          # Update the path to point to the correct build directory.
          path: godot-cpp
          key: ${{ runner.os }}-godot-cpp-cache
        continue-on-error: true

      - name: Run SCons for Linux
        run: scons platform=linux

      # Save cache after build
      - name: Save godot-cpp Cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: godot-cpp
          key: ${{ runner.os }}-godot-cpp-cache
          cache-limit: 2